server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      # This applies to ALL routes defined below
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
            key-resolver: "#{@ipKeyResolver}"
            
      routes:
        - id: identity-auth-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/ekart/v1/auth/**
        - id: identity-management-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/ekart/v1/identity/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/ekart/v1/products/**
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates: 
            - Path=/ekart/v1/inventory/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/ekart/v1/orders/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/ekart/v1/payments/**