server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: identity-service 
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/ekart/v1/auth/** 
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/ekart/v1/products/**
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates: 
            - Path=/ekart/v1/inventory/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/ekart/v1/orders/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/ekart/v1/payments/**
