spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # Note the 'native' keyword here instead of 'git'
          search-locations: ${file_location}

server:
  port: 8888