spring:
 application:
    name: config-server
 cloud:
  config:
   server:
    git:
     uri:https://github.com/SumanSana/ecommerce-microservices/config-repo
     username:${GIT_USERNAME}
     password:${GIT_PASSWORD}
  server:
   port:8888